### ISSUE TITLE
Screenshots of CMS within Readme

### ISSUE THREAD

**Issue by kakposoe** [Tendoo/cloud-breeze#7]
Would be good to have some screenshots so people know what to expect :smile:

**Comment by kakposoe** [comment]
@Blair2004 Look forward to seeing it.

**Comment by Blair2004** [comment]
![image](https://user-images.githubusercontent.com/5265663/52855383-8796ce80-3121-11e9-97ae-de203b6396a9.png)

**Comment by Blair2004** [comment]
![image](https://user-images.githubusercontent.com/5265663/52855417-9f6e5280-3121-11e9-9db5-9851e552500d.png)

**Comment by Blair2004** [comment]
![image](https://user-images.githubusercontent.com/5265663/52856253-34724b00-3124-11e9-8cb0-c27db5267d82.png)

**Comment by Blair2004** [comment]
![image](https://user-images.githubusercontent.com/5265663/52856336-6c798e00-3124-11e9-8f82-b3fddc522018.png)

**Comment by Blair2004** [comment]
![image](https://user-images.githubusercontent.com/5265663/52856378-887d2f80-3124-11e9-9fa6-6334901576f3.png)

**Comment by Blair2004** [comment]
![image](https://user-images.githubusercontent.com/5265663/52856731-79e34800-3125-11e9-9dd0-c7152d15ab63.png)
![image](https://user-images.githubusercontent.com/5265663/52856798-aac37d00-3125-11e9-98fa-d2aa4dd0657f.png)

**Comment by Blair2004** [comment]
![image](https://user-images.githubusercontent.com/5265663/52856818-bb73f300-3125-11e9-8e75-733734e94e1e.png)

**Comment by Blair2004** [comment]
![image](https://user-images.githubusercontent.com/5265663/52856852-d34b7700-3125-11e9-984d-8049e462143a.png)
![image](https://user-images.githubusercontent.com/5265663/52856871-dba3b200-3125-11e9-9010-624ba4e83545.png)
![image](https://user-images.githubusercontent.com/5265663/52856987-1dccf380-3126-11e9-87db-2998ef68822f.png)

**Comment by Blair2004** [comment]
![screenshot-user-images githubusercontent com-2019 02 15-13-55-12](https://user-images.githubusercontent.com/5265663/52858180-b749d480-3129-11e9-950a-c9216eacf0dc.png)
